### ISSUE TITLE
plugin does not recognize the the data source

### ISSUE THREAD

**Issue by ppatel26** [AquaQAnalytics/grafana-kdb-datasource-ws#12]
Hello, 

I have a grafana-server running on a DigitalOcean droplet, everything looks fine there
![image](https://user-images.githubusercontent.com/22735144/98307693-61b7fa00-1f94-11eb-985a-49d3175ff4d8.png)

I install the kdb plugin using `grafana-cli plugins install aquaqanalytics-kdbadaptor-datasource`, which installs the plugin properly, I see the plugin under *Others* when I click on *Add data source*

After which I am greeted to this

![image](https://user-images.githubusercontent.com/22735144/98308410-eeaf8300-1f95-11eb-93b9-560041f77fa2.png)

I have a kdb process running on `-p 9101`. I don't have any authentication on the process 

> I also applied the following in my kdb process as instructed 
``.z.ws:{ds:-9!x;neg[.z.w] -8! `o`ID!(@[value;ds[`i];{`$"'",x}];ds[`ID])}``

Not sure what I am doing wrong here that's causing the server not connect to the data source

**Comment by frenzy21** [comment]
Hi,

What version of kdb are you running ?

Regards,

James

On 5 Nov 2020, at 23:44, Parv Patel <notifications@github.com> wrote:

﻿

Hello,

I have a grafana-server running on a DigitalOcean droplet, everything looks fine there
[image]<https://user-images.githubusercontent.com/22735144/98307693-61b7fa00-1f94-11eb-985a-49d3175ff4d8.png>

I install the kdb plugin using grafana-cli plugins install aquaqanalytics-kdbadaptor-datasource, which installs the plugin properly, I see the plugin under Others when I click on Add data source

After which I am greeted to this

[image]<https://user-images.githubusercontent.com/22735144/98308410-eeaf8300-1f95-11eb-93b9-560041f77fa2.png>

I have a kdb process running on -p 9101. I don't have any authentication on the process

I also applied the following in my kdb process as instructed
.z.ws:{ds:-9!x;neg[.z.w] -8! `o`ID!(@[value;ds[`i];{`$"'",x}];ds[`ID])}

Not sure what I am doing wrong here that's causing the server not connect to the data source

**Comment by ppatel26** [comment]
Hey James, 

Sorry, should have added that info. 

I am using a 32bit KDB+ 3.6

**Comment by boyce-pj** [comment]
Hi,

I think the issue here might be the address that you're trying to access the kdb-datasource with. In your case, is the kdb+ instance located on the same machine as the browser you are accessing grafana from? Default grafana plugins connect to their datasource using the grafana-server as a proxy, but our kdb+ plugin connects the end user to the kdb+ database directly; thus the address used in the 'host' field needs to be relative to the end user and using 'localhost' might be the issue here. We would recommend avoiding the use of loopbacks and users should use full addresses instead e.g. hostname.domain.com:port or ip address:  aaa.bbb.ccc.ddd:port.

Also when you view your browser's console output (F12 for most browsers) do you see any errors when you press 'Save & Test'?

Kind Regards,

PJ

**Comment by ppatel26** [comment]
Yes the kdb instance is located in the same machine as the grafana server. Hence, I thought using `localhost:9101` would work just fine

I am accessing grafana using the `server-ip-address:3000` on my browser
